#!/bin/bash

# This is  a LESS processer instructions file

cd media/css

lessc common.less > common.css
lessc root.less > root.css
lessc workshop.less > workshop.css
lessc blog.less > blog.css
lessc video.less > video.css