#!/bin/bash
set +e

# This is  a LESS processer instructions file

# Awesomely LESS has a minifier built in, so we'll use that

cd media/css

# All files ahve charset in them as we want to have them as stand alone sheets
# When combining them, put the put the first one in and strip the rest (hence the tail -n +2)

cat common.less | lessc -x - screen.css
tail root.less -n +2 | lessc -x - >> screen.css
tail workshop.less -n +2 | lessc -x - >> screen.css
tail blog.less -n +2 | lessc -x - >> screen.css
tail video.less -n +2 | lessc -x - >> screen.css