#!/bin/bash
set +e

# Combine and minify all the js files into one file to save on requests and bytes

cd media/js

echo 'Begin smooshing searcher.js'

#  Minify the variable names.
#  Each script is put in its own function scope so other scripts should (in theroy) have no problems with this
cat searcher.js > temp
sed -i 's/noResults\b/z/g' temp
sed -i 's/searchBox\b/y/g' temp
sed -i 's/entries\b/x/g' temp
sed -i 's/searchTimeout\b/w/g' temp
sed -i 's/firstRun\b/v/g' temp
sed -i 's/loc\b/u/g' temp
sed -i 's/hist\b/s/g' temp     // Strange bug where if you use 't' it doest get inserted and you end up inserting `nothing`
sed -i 's/win\b/r/g' temp
sed -i 's/textToCheck\b/q/g' temp
sed -i 's/searchPattern\b/p/g' temp
sed -i 's/address\b/o/g' temp
sed -i 's/searchString\b/n/g' temp

# Function names
sed -i 's/clearFilter(/m(/g' temp
sed -i 's/filter(/l(/g' temp
sed -i 's/reset(/k(/g' temp
sed -i 's/handlePathChange(/j(/g' temp

cat temp > tmcscripts.js
rm temp
#cat tmcvideo.js >> tmcscripts.js

echo 'Finished with home brew scripts'
echo 'Begin removing unessary characters'

sed -i 's/\/\/.*//g' tmcscripts.js                # Dont need comments (and they become greedy when everything is on a single line)
sed -i 's/ #\*.*$//'g tmcscripts.js               # Dont need comments (and they become greedy when everything is on a single line)
sed -i '/console.*/'d tmcscripts.js               # Debug statements
sed -i 's/^[ ^t]*//' tmcscripts.js                # Leading whitespace and tabs N.B in theory there shouldnt need to be tabs anywhere but I am sure there will be
sed -i 's/[ ^t]*$//' tmcscripts.js                # Trailing whitespace and tabs
sed -i 's/ () /()/g' tmcscripts.js                # Spaces in 'function () {'
sed -i 's/ + /+/g' tmcscripts.js                  # Spaces in ' + '
sed -i 's/ || /||/g' tmcscripts.js                # Spaces in ' || '
sed -i 's/ += /+=/g' tmcscripts.js                # Spaces in ' += '
sed -i 's/for (/for(/g' tmcscripts.js             # Spaces in 'for ( ' Usually in a for loop
sed -i 's/; /;/g' tmcscripts.js                   # Spaces in '; ' Usually in a for loop
sed -i 's/ \(<\|<=\|>\|>=\) /\1/g' tmcscripts.js  # Spaces in ' < | > | <= | >= ' Usually in a for loop
sed -i 's/ \(+=\|-=\) /\1/g' tmcscripts.js        # Spaces in ' += | -= '
sed -i 's/ \(=\+\) /\1/g' tmcscripts.js           # Spaces in 'x = y', 'x == y', 'x === y'
sed -i 's/) {/){/g' tmcscripts.js                 # End of parameter list and opening curly brace
sed -i 's/if (/if(/g' tmcscripts.js               # End of if and opening round bracket
sed -i 's/, \(.\)/,\1/g' tmcscripts.js            # Comma space anything
sed -i ':a;N;$!ba;s/\n//g' tmcscripts.js          # New lines N.B. Put this at the end otherwise other operation (like get rid of leading white space) get confused

echo 'Finished with unnecessary characters'

echo 'Adding in GA (unmolested)'
# GS is already optimised and mucking with it furthur seems to break things so just append it at the end
cat ga.js >> tmcscripts.js
echo 'finished wiht GA'
echo 'Finished combining all JavaScript files'
