#!/bin/bash
set +e

if [[ $# -ne 2 || ( $1 != "mount" && $1 != "unmount" ) ]]; then
  echo "Usage:"
  echo "mounter mount   destination   # mount the remote destination"
  echo "mounter unmount destination   # unmount the remote destination"
  exit -1
fi

declare -A mountInfo

# Add mounts as needed
case $2 in
  "production")
    mountInfo=( [name]="the MetaCity production deploy"
                          [ref]="production"
                          [mountCommand]="sshfs doug@enc:/srv/http/tmc /media/tmc"
                          [unmountCommand]="sudo umount /media/tmc");;

  "admin")
    mountInfo=( [name]="the MetaCity admin"
                          [ref]="admin"
                          [mountCommand]="sshfs doug@enc:/home/doug/tmcadmin /home/doug/Code/theMetaCity/utils/remote"
                          [unmountCommand]="sudo umount /home/doug/Code/theMetaCity/utils/remote");;
  *) 
    echo "Unknown mount. Please provide a known mount."
    echo "Known mounts are: 'production', 'admin'"  # Have to update these manually as bash does not have nested mounts
    exit 2;;
esac

# Proper command found, time to execute it
echo "I am going to: "$1 ${mountInfo[name]}

if [ $1 == "mount" ]; then
  ${mountInfo[mountCommand]}
  if [[ $? -ne 0 ]]; then
    echo "Something went wrong with mounting. See errors above."
  else
    echo "Mounted successfully."
  fi
elif  [ $1 == "unmount" ]; then
  ${mountInfo[unmountCommand]}
  if [[ $? -ne 0 ]]; then
    echo "Something went wrong with unmounting. See errors above."
  else
    echo "Unmounted successfully."
  fi
fi
